B7B7D6BA
http://www.ccste.com/doudou/loader_files/Loader.exe
http://gamingonsteroids.com/loader_files/index.html
B2B14C91
http://gamingonsteroids.com/loader_files/lol/old.dll
7.15
F92E0B8A
http://gamingonsteroids.com/loader_files/lol/new.dll
7.16
http://gamingonsteroids.com/loader_files/dependencies/d3dx9_33.dll
http://gamingonsteroids.com/loader_files/dependencies/lua5.1.dll
http://gamingonsteroids.com/loader_files/dependencies/curl.exe
http://gamingonsteroids.com/loader_files/dependencies/lua52.dll
9E7D8FC4
http://gamingonsteroids.com/loader_files/lol/older.dll
7.14
-----------------------------------------------------
E0CF829C
http://gamingonsteroids.com/loader_files/lex/new.dll
7.16
9915AC8A
http://gamingonsteroids.com/loader_files/lex/old.dll
7.15
2D3E1FEE
http://gamingonsteroids.com/loader_files/lex/older.dll
7.14
-----------------------------------------------------
